## Basics

In [1]:
from primitives import Parameters
p = Parameters()

In [2]:
from ContinuousContract import ContinuousContract
cc=ContinuousContract(p)
(cc_J,cc_W)=cc.J()

In [3]:
from BasicContract import BasicContract

bc=BasicContract(3,cc.js,p)

(best_r,bc_J)=bc.J_K()

c:\Users\andre\Codes\Multi-worker firm\Contract approximation check\primitives.py:192: RuntimeWarning: divide by zero encountered in power
  return np.power(np.divide((1.0 - self.p.u_rho) * value + self.p.u_b, aa),


In [7]:
cc.js.re(150)

-7.91033905045424e-16

In [11]:
import numpy as np
best_r*bc.v_grid_0[:,np.newaxis]

array([[ 60.        ,  60.0326186 ,  60.06469021,  60.09667851,
         60.12908399,  60.16121628,  60.1928769 ,  60.22480378,
         60.25694278,  60.2886922 ],
       [ 70.        ,  70.02431958,  70.04859145,  70.07288075,
         70.09712185,  70.12130732,  70.14547788,  70.16968458,
         70.19381738,  70.21801608],
       [ 80.        ,  80.02241922,  80.04487214,  80.06729035,
         80.08968478,  80.11207167,  80.13446085,  80.15678745,
         80.17913327,  80.20141897],
       [ 90.        ,  90.0300662 ,  90.06019306,  90.09029552,
         90.12038592,  90.15047441,  90.18057226,  90.21059317,
         90.24064043,  90.27060749],
       [100.        , 100.1921897 , 100.39050115, 100.59464874,
        100.80419616, 101.01852354, 101.23675474, 101.45781523,
        101.68026311, 101.90239661]])

In [9]:
best_r

array([[1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5]])

In [4]:
bc.v_grid_0

array([ 60.,  70.,  80.,  90., 100.])

## Comparisons across contracts

In [38]:
cc_W[0,0]#=60.185
cc_J[0,0]

38.824856923006394

In [39]:
bc_J[0]

array([[40.01473302, 40.01312635, 40.01151621]])

In [61]:
bc_J[1].shape[1]

3

In [40]:
cc_W[0,4]#=69.78
cc_J[0,4]

37.41099219875538

In [41]:
bc_J[1]

array([[39.17391804, 39.17066896, 39.16741218]])

In [42]:
cc_W[0,15]#=79.79
cc_J[0,15]

34.96803443009572

In [43]:
bc_J[2]

array([[36.91026283, 36.90223643, 36.89419202]])

In [44]:
cc_W[0,45]#=90.01
cc_J[0,45]

30.034413428422376

In [45]:
bc_J[3]

array([[30.86393696, 30.83549673, 30.80696827]])

In [46]:
cc_W[0,99]
cc_J[0,99]

16.986493446281656

In [47]:
bc_J[4]

array([[15.25811404, 14.97183464, 14.68161178]])

In [5]:
15.25811404/16.986493446281656

0.8982497822904115

In [48]:
cc_W[0,197]#=110
cc_J[0,197]

-206.37148108933917