## Basics

In [1]:
from primitives import Parameters
p = Parameters()

In [2]:
from ContinuousContract import ContinuousContract
cc=ContinuousContract(p)
(cc_J,cc_W)=cc.J()

In [3]:
from BasicContract_r import BasicContract_r

bc=BasicContract_r(3,cc.js,p)

(bcr_J,bcr_W)=bc.J_K()

w_star: [[[0.         0.         0.06213958]
  [0.         0.         0.08042259]
  [0.         0.         0.09921045]
  [0.         0.         0.11828158]
  [0.         0.         0.1375303 ]
  [0.         0.         0.15689898]
  [0.         0.         0.17635315]
  [0.         0.         0.19587078]
  [0.         0.         0.21543704]
  [0.         0.         0.23504154]
  [0.         0.         0.25467675]
  [0.         0.         0.27433705]
  [0.         0.         0.2940182 ]
  [0.         0.         0.31371686]
  [0.         0.         0.33343042]
  [0.         0.         0.35315678]
  [0.         0.         0.37289424]
  [0.         0.         0.39264139]
  [0.         0.         0.41239707]
  [0.         0.         0.43216031]
  [0.         0.         0.45193027]
  [0.         0.         0.47170627]
  [0.         0.         0.49148769]
  [0.         0.         0.51127402]
  [0.         0.         0.53106481]
  [0.         0.         0.55085967]
  [0.         0.         0.570

c:\Users\andre\Codes\Multi-worker firm\cont_ap_ch\primitives.py:169: RuntimeWarning: divide by zero encountered in power
  return np.divide(aa * np.power( wage, self.p.tax_lambda * (1.0 - self.p.u_rho)) - self.p.u_b,
c:\Users\andre\Codes\Multi-worker firm\cont_ap_ch\search.py:192: RuntimeWarning: invalid value encountered in add
  return self.re_cst - self.x[0]*e + self.x[1]/(1+self.x[2])*np.power( np.abs( e - self.e_asy), 1 + self.x[2])
c:\Users\andre\Codes\Multi-worker firm\cont_ap_ch\valuefunction.py:27: RuntimeWarning: invalid value encountered in subtract
  Xi_arg = (Xmax + np.exp(gamma[3]) - Xi)/100.0
c:\Users\andre\Codes\Multi-worker firm\cont_ap_ch\valuefunction.py:11: RuntimeWarning: invalid value encountered in subtract
  Xi_arg = (Xmax + np.exp(gamma[3]) - Xi)/ 100.0
c:\Users\andre\Codes\Multi-worker firm\cont_ap_ch\valuefunction.py:32: RuntimeWarning: invalid value encountered in subtract
  Xi_arg = (Xmax + np.exp(gamma[3]) - Xi)/100.0
c:\Users\andre\Codes\Multi-worker firm

AssertionError: pe is not NaN

In [ ]:
from BasicContract import BasicContract

bc=BasicContract(3,cc.js,p)

(best_r,bc_J)=bc.J_K()

In [ ]:
cc.js.re(150)

In [ ]:
import numpy as np
best_r*bc.v_grid_0[:,np.newaxis]

In [ ]:
best_r

In [ ]:
bc.v_grid_0

## Comparisons across contracts

In [ ]:
cc_W[0,0]#=60.185
cc_J[0,0]

In [ ]:
bc_J[0]

In [ ]:
bc_J[1].shape[1]

In [ ]:
cc_W[0,4]#=69.78
cc_J[0,4]

In [ ]:
bc_J[1]

In [ ]:
cc_W[0,15]#=79.79
cc_J[0,15]

In [ ]:
bc_J[2]

In [ ]:
cc_W[0,45]#=90.01
cc_J[0,45]

In [ ]:
bc_J[3]

In [ ]:
cc_W[0,99]
cc_J[0,99]

In [ ]:
bc_J[4]

In [ ]:
15.25811404/16.986493446281656

In [ ]:
cc_W[0,197]#=110
cc_J[0,197]