## Basics

In [1]:
from primitives import Parameters
p = Parameters()

In [2]:
from ContinuousContract import ContinuousContract
cc=ContinuousContract(p)
(cc_J,cc_W,cc_Wstar)=cc.J()

In [3]:
from BasicContract_r import BasicContract_r

bc=BasicContract_r(5,cc.js,p)

(bcr_J,bcr_W)=bc.J_K()

In [57]:
bcr_W[0,24,:]
#bcr_J[0,24,:]

array([15.27295433, 15.83083595, 16.23173365, 16.3040549 , 16.3040549 ])

In [56]:
cc_W[0,90]
#cc_J[0,90]
#cc_Wstar[0,90]

15.446763609841662

In [32]:
bcr_W[0,10,:]
bcr_J[0,10,:]

array([80.37330498, 61.34829157, 37.74631678, 27.14466755, 26.48969014])

In [31]:
cc_W[0,41]
cc_J[0,41]

132.95227071155387

In [40]:
cc_W[0,99]
cc_J[0,99]

22.21927746547145

In [6]:
cc_Wstar[0,47]

70.45571150552406

In [30]:
bcr_W[0,48,0]
bcr_J[0,48,0]

28.19511365412852

In [46]:
cc_W[0,3]
#cc_J[0,3]
#cc_Wstar[0,3]

39.5094092600252

In [14]:
bcr_J[0,50,:]

array([34.23056457, 26.48969019, 26.48969019, 26.48969019, 26.48969019])

In [11]:
bcr_W[0,40,:]
#bcr_J[0,3,:]

array([15.8296092 , 16.23373836, 16.3040549 , 16.3040549 , 16.3040549 ])

In [ ]:
from BasicContract import BasicContract

bc=BasicContract(3,cc.js,p)

(best_r,bc_J)=bc.J_K()

In [ ]:
cc.js.re(150)

In [ ]:
import numpy as np
best_r*bc.v_grid_0[:,np.newaxis]

In [ ]:
best_r

In [ ]:
bc.v_grid_0

## Comparisons across contracts

In [ ]:
cc_W[0,0]#=60.185
cc_J[0,0]

In [ ]:
bc_J[0]

In [ ]:
bc_J[1].shape[1]

In [ ]:
cc_W[0,4]#=69.78
cc_J[0,4]

In [ ]:
bc_J[1]

In [ ]:
cc_W[0,15]#=79.79
cc_J[0,15]

In [ ]:
bc_J[2]

In [ ]:
cc_W[0,45]#=90.01
cc_J[0,45]

In [ ]:
bc_J[3]

In [ ]:
cc_W[0,99]
cc_J[0,99]

In [ ]:
bc_J[4]

In [ ]:
15.25811404/16.986493446281656

In [ ]:
cc_W[0,197]#=110
cc_J[0,197]